version: '3'
services:
  nginx:
    build: 
      context: .
    image: damiansilbergleithcunniff/nginx-selfsigned:0.1.6
    environment:
      DOMAIN: "localhost"
      VALID_DAYS: 365
      ALT_NAMES: "*.lcl"
    volumes: 
      - ./conf:/etc/nginx/conf.d
    ports: 
     - 443:443
